// services folder is the redux way of fetching data

// Create API to be fetched by redux

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

// from rapidAPI
const apiHeaders = {
    'X-RapidAPI-Host': 'coinranking1.p.rapidapi.com',
    'X-RapidAPI-Key': '4d14269acemsh25772768c61ae02p17dd71jsn433a92d0f8c4'
} 

const baseUrl = 'https://coinranking1.p.rapidapi.com';
const createRequest = (endpoint) => ({ url : endpoint, headers: apiHeaders });

// This will connent this API with the store
export const cryptoAPI = createApi({
    reducerPath: 'cryptoAPI',
    baseQuery: fetchBaseQuery({ baseUrl }),
    // All the queries we want to fetch data from goes below
    endpoints: (builer) => ({
        getCryptos : builer.query({
            query: () => createRequest('/coins'),
        })
    })
});

// These custom hooks will be generated by redux which can be used by components to fetch data from specific endpoint
export const { useGetCryptosQuery } = cryptoAPI; 